import { Employee } from "./Shared/Models/Employee";
export const employees : Employee[] = [
  {
    id:1,
    name:'Manish Rathva',
    age:21,
    gender:'male',
    designation:'Angular Intern',
    email:'manish@gmail.com',
    imageUrl:'assets/image/download1.png',
  },
  {
    id:2,
    name:'Pramod Dodiya',
    age:21,
    gender:'male',
    designation:'Angular Intern',
    email:'Pramod@gmail.com',
    imageUrl:'assets/image/download1.png',
  },
  {
    id:3,
    name:'Preet Patel',
    age:21,
    gender:'male',
    designation:'React-Js Intern',
    email:'Preet@gmail.com',
    imageUrl:'assets/image/download1.png',
  },
  {
    id:4,
    name:'Vishal kumar',
    age:21,
    gender:'male',
    designation:'SEO',
    email:'vishal@gmail.com',
    imageUrl:'assets/image/download1.png',
  },
  {
    id:5,
    name:'Dhruv kumar',
    age:21,
    gender:'male',
    designation:'React-Js Intern',
    email:'Dhruv@gmail.com',
    imageUrl:'assets/image/download1.png',
  },
  {
    id:6,
    name:'Jayesh bilwal',
    age:21,
    gender:'male',
    designation:'Angular Intern',
    email:'jayesh@gmail.com',
    imageUrl:'assets/image/download1.png',
  },

]
